### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by wmadden** [abe33/atom-project-palette-finder#40]
1. CMD-SHIFT-P "Palette: view"

Sorry I can't be more specific, I didn't do anything else.

This is a project with loads of `.scss`, bower components with CSS and node modules with CSS. Let me know if there's anything else I can tell you.

**Atom Version**: 0.206.0
**System**: Mac OS X 10.10.3
**Thrown From**: [project-palette-finder](https://github.com/abe33/atom-project-palette-finder) package, v2.4.17
### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:128

TypeError: undefined is not a function
  at new ProjectPaletteColorView (/Users/wmadden/.atom/packages/project-palette-finder/lib/project-palette-color-view.coffee:20:48)
  at CoffeeCompileView.module.exports.CoffeeCompileView.buildColors (/Users/wmadden/.atom/packages/project-palette-finder/lib/project-palette-view.coffee:111:18)
  at CoffeeCompileView.module.exports.CoffeeCompileView.setPalette (/Users/wmadden/.atom/packages/project-palette-finder/lib/project-palette-view.coffee:79:6)
  at /Users/wmadden/.atom/packages/project-palette-finder/lib/project-palette-finder.coffee:165:16
  at _fulfilled (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:794:54)
  at self.promiseDispatch.done (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:823:30)
  at Promise.promise.promiseDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:756:13)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:516:49
  at flush (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:110:17)
  at process._tickCallback (node.js:357:13)

```
### Commands

```
     -1:38.5.0 pane:show-previous-item (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -1:37.5.0 pane:show-next-item (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -1:32.8.0 settings-view:open (atom-text-editor.editor.vim-mode.command-mode.is-focused)
  2x -1:27.7.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -1:23.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:28.3.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -0:28.1.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:25 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:06.1.0 core:close (atom-workspace.workspace.scrollbars-visible-always.theme-one-light-syntax.theme-one-light-ui)
     -0:05.4.0 pane:show-previous-item (atom-workspace.workspace.scrollbars-visible-always.theme-one-light-syntax.theme-one-light-ui)
     -0:04.5.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-light-syntax.theme-one-light-ui)
     -0:02.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:02.5.0 palette:view (atom-workspace.workspace.scrollbars-visible-always.theme-one-light-syntax.theme-one-light-ui)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "autosave",
      "merge-conflicts"
    ],
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
circle-ci, v0.10.0
color-picker, v2.0.4
language-babel, v0.7.0
language-haml, v0.21.0
language-jade, v0.4.0
language-prolog, v0.9.0
linter, v0.12.6
linter-coffeelint, v0.3.1
linter-eslint, v0.5.8
minimap, v4.9.4
project-palette-finder, v2.4.17
vim-mode, v0.51.0

# Dev
No dev packages
```

**Comment by abe33** [comment]
Hi, thanks for the report, the problem comes from the new deprecation policy in 0.206.
Actually I've stopped maintaining this package as I've merged it's functionalities within [pigments](https://atom.io/packages/pigments). Have you tried it? 
I could publish a quick patch if you're really not willing to use pigments instead, but I would prefer avoiding that.

**Comment by derEremit** [comment]
Is there a methotology for marking a package obsolete?
Releasing a version that hints to pigments or something like that?
