### ISSUE TITLE
Failed to activate the project-palette-finder package

### ISSUE THREAD

**Issue by nmccready** [abe33/atom-project-palette-finder#41]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.209.0
**System**: Mac OS X 10.10.3
**Thrown From**: [project-palette-finder](https://github.com/abe33/atom-project-palette-finder) package, v2.4.17
### Stack Trace

Failed to activate the project-palette-finder package

```
At undefined is not a function

TypeError: undefined is not a function
  at ProjectPaletteFinder.scanProject (/Users/nem/.atom/packages/project-palette-finder/lib/project-palette-finder.coffee:226:6)
  at ProjectPaletteFinder.activate (/Users/nem/.atom/packages/project-palette-finder/lib/project-palette-finder.coffee:100:6)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:240:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:221:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:165:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:213:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:436:29
  at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
  at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:431:19)
  at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:412:46)
  at Atom.module.exports.Atom.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom.js:641:21)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:95:23)
  at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:36:7)

```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "seti-ui",
      "monokai-seti"
    ],
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "atom-color-highlight"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Stylus, v1.0.0
atom-jade, v0.3.0
atom-text-transformer, v0.7.0
autoclose-html, v0.17.1
autocomplete-paths, v1.0.2
coffee-compile, v0.16.0
color-picker, v2.0.4
command-logger, v0.23.0
hide-files, v0.1.7
highlight-line, v0.10.2
highlight-selected, v0.9.3
indent-guide-ext, v0.2.1
jslint, v1.4.0
language-coffee-script, v0.38.1
language-jade, v0.4.0
language-nginx, v0.5.3
language-scala, v1.1.3
language-stylus, v0.2.0
linter-scalac, v0.3.4
monokai-seti, v0.7.0
open-recent, v2.2.4
pain-split, v1.4.0
project-palette-finder, v2.4.17
seti-ui, v0.7.1
svg-preview, v0.6.0
tabular, v0.1.0

# Dev
No dev packages
```

**Comment by abe33** [comment]
Hi @nmccready, do you know I'm no longer maintaining this package? It's now replaced by [pigments](http://atom.io/packages/pigments) that includes the features from both `project-palette-finder` and `atom-color-highlight`.

**Comment by nmccready** [comment]
cool
