### ISSUE TITLE
Failed to activate the project-palette-finder package: undefined is not a function

### ISSUE THREAD

**Issue by ronakrrb** [abe33/atom-project-palette-finder#43]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.4
**Thrown From**: [project-palette-finder](https://github.com/abe33/atom-project-palette-finder) package, v2.4.17
### Stack Trace

Failed to activate the project-palette-finder package

```
At undefined is not a function

TypeError: undefined is not a function
    at ProjectPaletteFinder.scanProject (/Users/sardar/.atom/packages/project-palette-finder/lib/project-palette-finder.coffee:273:17)
    at ProjectPaletteFinder.activate (/Users/sardar/.atom/packages/project-palette-finder/lib/project-palette-finder.coffee:104:19)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:240:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:221:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:165:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:213:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:436:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:431:19)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "autocomplete",
      "atomatigit"
    ],
    "themes": [
      "seti-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "project-palette-finder": {
    "paletteSort": true
  }
}
```
### Installed Packages

``` coffee
# User
autoclose-html, v0.18.0
color-picker, v2.0.7
copy-filename, v1.0.1
git-tab-status, v1.9.2
html2haml, v0.10.0
language-haml, v0.21.0
minimap, v4.10.1
minimap-color-highlight, v4.1.4
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.3
minimap-highlight-selected, v4.3.0
minimap-selection, v4.3.0
pretty-json, v0.4.1
project-palette-finder, v2.4.17
seti-ui, v0.7.1

# Dev
No dev packages
```

**Comment by abe33** [comment]
This package have been deprecated since some time now, but as Atom doesn't have a mechanism to notify user about it yet I couldn't do much. It has been replaced by [pigments](http://atom.io/packages/pigments) that combine this package with `atom-color-highlight` and improves the overall performances.
