### ISSUE TITLE
Type Error: undefined is not a function

### ISSUE THREAD

**Issue by kohenkatz** [abe33/atom-project-palette-finder#44]
Steps to reproduce:
1. Right-click on a folder in Windows Explorer and choose "Open with Atom" from the context menu.

**Atom Version**: 1.0.2
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [project-palette-finder](https://github.com/abe33/atom-project-palette-finder) package, v2.4.17
### Stack Trace

Failed to activate the project-palette-finder package

```
At undefined is not a function

TypeError: undefined is not a function
    at ProjectPaletteFinder.scanProject (/C:/Users/moshe/.atom/packages/project-palette-finder/lib/project-palette-finder.coffee:273:17)
    at ProjectPaletteFinder.activate (/C:/Users/moshe/.atom/packages/project-palette-finder/lib/project-palette-finder.coffee:104:19)
    at Package.module.exports.Package.activateNow (C:\Users\moshe\AppData\Local\atom\app-1.0.2\resources\app.asar\src\package.js:240:19)
    at C:\Users\moshe\AppData\Local\atom\app-1.0.2\resources\app.asar\src\package.js:221:30
    at Package.module.exports.Package.measure (C:\Users\moshe\AppData\Local\atom\app-1.0.2\resources\app.asar\src\package.js:165:15)
    at Package.module.exports.Package.activate (C:\Users\moshe\AppData\Local\atom\app-1.0.2\resources\app.asar\src\package.js:213:14)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\moshe\AppData\Local\atom\app-1.0.2\resources\app.asar\src\package-manager.js:452:21)
    at AtomColorHighlight.activate (/C:/Users/moshe/.atom/packages/atom-color-highlight/lib/atom-color-highlight.coffee:58:25)
    at Package.module.exports.Package.activateNow (C:\Users\moshe\AppData\Local\atom\app-1.0.2\resources\app.asar\src\package.js:240:19)
    at C:\Users\moshe\AppData\Local\atom\app-1.0.2\resources\app.asar\src\package.js:221:30
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "projectHome": "C:\\Web\\",
    "themes": [
      "atom-dark-ui",
      "solarized-dark-syntax"
    ],
    "disabledPackages": [
      "welcome",
      "project-palette-finder"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-color-highlight, v3.0.9
file-icons, v1.5.8
highlight-line, v0.11.0
highlight-selected, v0.10.1
language-csharp, v0.6.0
linter, v1.2.0
linter-js-yaml, v1.1.1
minimap, v4.11.0
minimap-highlight-selected, v4.3.0
package-manager-commands, v2.0.3
project-palette-finder, v2.4.17
set-syntax, v0.3.0
typewriter, v0.3.3

# Dev
No dev packages
```

**Comment by abe33** [comment]
Hi @kohenkatz, this package is no longer maintained, and have been replaced by [pigments](http://atom.io/packages/pigments).

**Comment by kohenkatz** [comment]
@abe33 This ticket was created by clicking the "Create a Ticket" button in the error message that shows up inside Atom.  There is no way to see the message in the README that says that the plugin is not maintained until after you have submitted an issue.

Maybe you can release an update to this plugin that disables itself somehow in order to prevent this from happening to other people? (I don't know if that is possible in the Atom plugin system, but it would probably be helpful to do it if it can be done.)

**Comment by abe33** [comment]
Yeah, sorry, actually I did that, but only when pigments is installed, and I also unpublished this package so it's now a bit late to push an update.
